### ISSUE TITLE
Customize index storage

### ISSUE THREAD

**Issue by matklad** [fitzgen/id-arena#1]
Hi! This might be a premature optimization, but I am slightly concerned that the size of the index is `2 * size_of::<usize>()`. I'd rather use `NonZeroU32` as an index. 

What do you think about making the index representation generic?

Something like

```Rust
trait ArenaIndex: Clone + Copy {
    fn from_usize(arena_idx: usize, item_idx: usize) -> Option<Self>;
    fn to_usize(self) -> (Option<usize>, usize);
}

struct Idx<T, I: ArenaIndex = (usize, usize)> {
    idx: I
    ...
}
```

**Comment by matklad** [comment]
Related problem: when using indexes, I tend to write inherent impls on the ID:

```Rust
impl ModuleId {
    fn source(self, tree: &ModuleTree) -> ModuleSource {
        tree.module(self).source
    }
    fn parent_link(self, tree: &ModuleTree) -> Option<LinkId> {
        tree.module(self).parent
    }
    fn parent(self, tree: &ModuleTree) -> Option<ModuleId> {
        let link = self.parent_link(tree)?;
        Some(tree.link(link).owner)
    }
}
```

If, however, I use `id_arena` and define `ModuleId = id_arena::Id<ModuleData>`, I lose the ability to define inherent impls. So, an alternative design here would be some kind of macro to allow user to define indices (which probably is out of scope for this crate though...).

**Comment by matklad** [comment]
>So, an alternative design here would be some kind of macro to allow user to define indices (which probably is out of scope for this crate though...).

Actually, I can easily solve this by defining my own ID as `struct Id<T>(id_arena::Id<T>)` and writing a bunch of trivial impls once.

**Comment by fitzgen** [comment]
I like this idea.

I too was concerned about the size, but at the same time have never actually run into problems because of it, but also probably because I haven't used this in anything that has received very much profiling or perf work.

I think rather than making the `Id` type be generic over some "essence of `Id`" type, we should just make the whole arena generic over an `Id` type (which we would have to do anyways).

I'll whip up a strawman and ping you for feedback.

**Comment by matklad** [comment]
> we should just make the whole arena generic over an Id type (which we would have to do anyways).

Note that having a built-in Id type is useful though: `type FooId = Id<Foo>` is more ergonomic than defining your own `#derive(everything) struct FooId(u32)`;. Perhaps we can do both? Parametrize `Arena` over `Id: ArenaId` *and* make a bunch of build-in types like `CheckedUsizeId`, `U32Id`. 

OTOH, if, due to coherence, users are better served by defining their own Id types anyway, the best solution might be just a paragraph in the docs: "here's an example that defines `usize` Id. Copy-paste this in your crate, replacing `usize` with something more compact, if necessary".
