### ISSUE TITLE
Feature Request: Id-based Map Type (or support for independently implementing)

### ISSUE THREAD

**Issue by esoterra** [fitzgen/id-arena#16]
I'm working on a compiler project and have found it useful to have an `Arena` of expression AST nodes and to store other useful computed information about the expressions (e.g. the span in code they refer to, their type) in auxiliary data structures keyed by the `Id` of the expression.

Since the `Id`s are continuous and zero-indexed, you can implement a map with key type `Id<T>` using a simple `Vec<V>`. This combination of `Arena` and "Arena Map" is a nice simple type-safe efficient way of implementing structure-of-arrays, ECS, etc. efficiently.

I have implemented this in my codebase naively [here](https://github.com/wrought-lang/wrought/blob/857d11b718d782a3fa92bc9a62a531115e84752b/src/id_map.rs) but it would nice to either A) have this built in to the `id-arena` crate or for the crate to let me read the `arena_id` of an `Id<T>` so that I can validate that the map keys are all from the same arena like `Arena` itself does.

Another advantage to having it in this crate is that we could have a method `new_map(&self) -> ArenaMap<T, V>` on `Arena<T>` that constructs a new map, sets its internal `arena_id` (without making that visible), and allocate capacity for enough entries as there are currently elements in the `Arena`.

**Comment by fitzgen** [comment]
You're probably better off using `cranelift-entity` at this point. This crate is intentionally very simple.
