### ISSUE TITLE
replace `next_id` with `alloc_with_id`

### ISSUE THREAD

**Issue by matklad** [fitzgen/id-arena#9]
```
fn alloc_with_id(f: impl FnOnce(ID) -> T)
```

seems like potentially more bullet-proof API?

**Comment by fitzgen** [comment]
Unless there is also an assertion against re-entrancy, I don't think this actually removes potential bugs resulting from operation orderings like

1. get next id (either via `next_id` or `alloc_with_id`)
2. "unexpected" alloc
3. alloc the thing trying to use the id gotten in (1)

I'm not convinced it is worth adding the overhead that an assertion against re-entrancy would require...

**Comment by matklad** [comment]
`alloc` takes `&mut`, so no reentrancy is possible

**Comment by fitzgen** [comment]
Ah! great point! Yeah, I'd be in favor of this then!
